spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uber
    username: root
    password: 123456

    jpa:
      hibernate:
        show-sql: true
        properties:
          hibernate:
            format_sql: true